### ISSUE TITLE
Please support AppImage update information, libappimageupdate

### ISSUE THREAD

**Issue by probonopd** [antony-jr/GHReleaseBridge#1]
(Moved from https://github.com/Skycoder42/QtAutoUpdater/issues/8)

Hey @antony-jr please check out [libappimageupdate](https://github.com/AppImage/AppImageUpdate). It implements the update information mechanisms described in the [AppImageSpec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information).

> update AppImages directly from GitHub Releases (for now it does not use zsync , just raw copy! ). 

We are not interested in that, sorry. But if you integrate [libappimageupdate](https://github.com/AppImage/AppImageUpdate/wiki/Guide-to-libappimageupdate) we might be interested. I am sure that @TheAssassin is happy to answer any questions you might have.

**Comment by antony-jr** [comment]
@probonopd  sounds simple , I'm **happy** to take this job!

**Comment by antony-jr** [comment]
@probonopd this is moved to a new project https://github.com/antony-jr/AppImageBridge

**Comment by probonopd** [comment]
Thanks @antony-jr
